### ISSUE TITLE
v11 compatibility

### ISSUE THREAD

**Issue by STBaf** [OctarineSourcerer/cyberpunk2020#127]
Surely known (just as possible to-do - I know about the time problem reading the other issues) game system seem not to work on v11.

For example weapon roll:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'system')
    at CyberpunkActor.realSkillValue (actor.js:204:22)
    at CyberpunkActor.getSkillVal (actor.js:213:27)
    at CyberpunkItem.attackRoll (item.js:264:31)
    at CyberpunkItem.__fullAuto (item.js:278:33)
    at CyberpunkItem.__weaponRoll (item.js:220:19)
    at Object.onConfirm (actor-sheet.js:228:42)
    at modifiers.js:81:22

Maybe when there is time :-)

**Comment by STBaf** [comment]
Damn, sorry - forget it - just missed adding the Handgun skill *facepalm*
