### ISSUE TITLE
Update to 0.8.6: basic skill not appearing in character sheet.

### ISSUE THREAD

**Issue by vicsufer** [OctarineSourcerer/cyberpunk2020#81]
Hi guys, great job you're doign here.
I've updated the core system and then cyberpunk2020 system:
- core v0.7.6 -> v0.8.6
- cyberpunk2020: v0.2.4 -> v0.3.1

Migrations seems to fail for basic skills and the character sheet appears empty,
![image](https://user-images.githubusercontent.com/15276132/122614695-7199cf80-d087-11eb-868d-23428e1d8b8b.png)

 I'm getting the following logs:
```sh

FoundryVTT | 2021-06-18 20:25:07 | [error] ENOENT: no such file or directory, rename '/data/Data/systems/cyberpunk2020/packs/default-skills.db~' -> '/data/Data/systems/cyberpunk2020/packs/default-skills.db'

Error: ENOENT: no such file or directory, rename '/data/Data/systems/cyberpunk2020/packs/default-skills.db~' -> '/data/Data/systems/cyberpunk2020/packs/default-skills.db'

# More and more attemps with the same output (Up to 10 or so)
```
Also when reloading the browser I get the following logs:
```sh
FoundryVTT | 2021-06-18 20:38:45 | [error] The cyberpunk2020.default-skills Datastore is not yet connected!
Error: The cyberpunk2020.default-skills Datastore is not yet connected!
    at Function.get db [as db] (file:///home/foundry/resources/app/dist/database/backend/server-document.mjs:1:625)
    at ServerDatabaseBackend._getDocuments (file:///home/foundry/resources/app/dist/database/backend/server-backend.mjs:1:975)
    at ServerDatabaseBackend.get (file:///home/foundry/resources/app/common/abstract/backend.mjs:27:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
````

I have a backup of my old data, however is there any quickfix or workaround?

**Comment by OctarineSourcerer** [comment]
Huuuh. It looks like the `default-skills` compendium isn't being found for some reason. A couple questions:
- What do the contents of the `cyberpunk2020/packs` folder look like?
- Do the other compendiums work?

In the meantime, try hitting F12, open the console tab, and run `game.cyberpunk.migrateWorld()`, and see what that does :)

**Comment by vicsufer** [comment]
So a few updates on this:
- New created characters does have skills on the sheet.
- Only characters with allocated points on skills had their skills "dissapear"
- My players reported that they can sometimes see skills after switching tabs (I could't get to reproduce this behaviour, maybe its something GM related)
- Inspecting `world/worldname/data/actors.db` characters have their skills and values on the json.
- After restarting the server, no errors appear in the server/browser log.

The `cyberpunk2020/packs` folder does contain default-skills.db file, and as new characters are created the skills are on the sheet may no relate to missing files.

After running `game.cyberpunk.migrateWorld()``some characters recovered its skills partially while some others are still blank. 🤷  (No errors executing the migrateWorld function)

For now I will create new character sheets as it is not very painful (I'm still in campaign prep) but I will preserve old sheets in case you want to perform further test/debugging. I can also provide a compressed versionof the pre-migrated world folder if desired.

**Comment by OctarineSourcerer** [comment]
Those updates will help a lot, thank you! I'm almost certain that the problem is to do with migration. Really hoped I'd gotten the last of the bugs in that one, but apparently not.

A compressed version of the pre-migrated world would be amazing, thank you!

**Comment by OctarineSourcerer** [comment]
@vicsufer Still got that zip around? Don't think I'll be able to reproduce without as it stands

**Comment by vicsufer** [comment]
Sorry for the late response, I had a busy week.
The migration was made with your version not the one with the spanish translation.
Here's a link to my premigrated world, hope it is useful. https://mega.nz/file/9JNxQYyA#EISg4laaNr6uKNH8vbT_BFjBkwxGdZQQ9LsxhiVAfWs
